name: Create_issues
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:  
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: SF deploy     
      run: |
        export HOME=/root
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        echo ${{ secrets.sfdx_url }}  > env.sfdx
        sfdx force:auth:sfdxurl:store -d -a myTarget -f env.sfdx
        exit 1
    #- name: Notify failed build
    #  uses: jayqi/failed-build-issue-action@v1
    #  if: failure()
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify failed build
      run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Scheduled validation failed" --body "UAT Full repo validation has failed. Check the logs here **${{ github.workflow }}**" --assignees "@me" --label "build failed"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}