name: QA_Deploy
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/Deploy-Template.yml
    secrets:
      sfdx_url: ${{ secrets.DEMO_QA }}
