# This is a basic workflow to help you get started with Actions

name: Run_Code_analyzer

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Code_Scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Install Salesforce CLI Code Analyzer plugin
      - name: 'Install Salesforce CLI Code Analyzer plugin'
        run: |
          npm install @salesforce/cli --global
          sf plugins install code-analyzer

      # Run Code Analyzer
      - name: 'Run Code Analyzer'
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
            run-arguments: --workspace "force-app/main/default" --view detail --output-file "sca-results.csv" --config-file "code-analyzer.yml"
            results-artifact-name: code-analyzer-results

      # Check for Code Analyzer critical or high severity violations
      - name: 'Check for Code Analyzer critical or high severity violations'
        if: |
            steps.run-code-analyzer.outputs.exit-code > 0 ||
            steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
            steps.run-code-analyzer.outputs.num-sev2-violations > 0
        run: |
            sf code-analyzer rules --rule-selector regex
            echo One of more Code Analyzer critical or high severity violations found
            exit 1